sequenceDiagram
    participant AUT as AUTORIZADOR
    box rgb(225,245,238) account-posting
    participant APA as Pod A
    end
    participant KC as Kafka - comando-conta
    participant CT as Conta
    participant KR as Kafka  - retorno comando
    participant CK as Compass kafka
    box rgb(225,245,238) account-posting
    participant APB as Pod B
    end
    box rgb(250,236,231) Redis
    participant RED as Redis
    end

    APA-->>RED: 0. SUBSCRIBE canal de resposta (startup)
    APB-->>RED: 0. SUBSCRIBE canal de resposta (startup)

    AUT->>APA: 1. requisição gRPC
    activate APA
    APA->>KC: 2. produz no comando-conta
    KC->>CT: 3. consome evento
    Note over CT: gera lançamento em conta corrente
    CT->>KR: 4. produz retorno-conta
    KR->>CK: 5. consome evento
    CK->>APB: 6. requisição de retorno
    activate APB
    APB->>RED: 7. publish resultado (canalId)
    deactivate APB
    RED-->>APA: 8. entrega ao subscriber Pod A
    APA-->>AUT: 9. resposta gRPC
    deactivate APA
